/**
 * CKD High-Risk Patient Monitoring Service
 *
 * Implements the CKD risk monitoring algorithm that scans patients and identifies
 * those requiring urgent monitoring based on clinical criteria.
 * Based on KDIGO guidelines and best practices.
 */

import { getPatientList } from './patientService';
import { PatientListItem } from '../types/patient';

/**
 * Alert generated by the risk assessment
 */
export interface RiskAlert {
  severity: 'CRITICAL' | 'HIGH' | 'MODERATE';
  code: string;
  message: string;
  action: string;
}

/**
 * Priority level for patient monitoring
 */
export type MonitoringPriority = 'CRITICAL' | 'HIGH' | 'MODERATE' | 'LOW';

/**
 * High-risk patient assessment result
 */
export interface HighRiskPatientAssessment {
  patient_id: string;
  name: string;
  mrn: string;
  age: number;
  gender: string;
  stage: number;
  egfr: number;
  egfr_trend: string;
  egfr_change: number;
  comorbidities: string[];
  alerts: RiskAlert[];
  alert_count: number;
  severity_score: number;
  priority: MonitoringPriority;
  requires_monitoring: boolean;
}

/**
 * Scan results with statistics
 */
export interface ScanResults {
  scan_date: string;
  total_patients_scanned: number;
  high_risk_patients: number;
  high_risk_percentage: number;
  priority_distribution: {
    CRITICAL: number;
    HIGH: number;
    MODERATE: number;
  };
  alert_frequency: Record<string, number>;
  patients: HighRiskPatientAssessment[];
}

/**
 * Assess a single patient's risk level and generate alerts
 */
export function assessPatientRisk(patient: PatientListItem): HighRiskPatientAssessment {
  const alerts: RiskAlert[] = [];
  let severity_score = 0;

  // Helper function to safely convert to number
  const toNumber = (value: number | string | undefined): number => {
    if (value === undefined || value === null) return 0;
    const num = typeof value === 'string' ? parseFloat(value) : value;
    return isNaN(num) ? 0 : num;
  };

  // Extract key values and ensure they are numbers
  const eGFR = toNumber(patient.latest_observations?.eGFR);
  const eGFRTrend = patient.latest_observations?.eGFR_trend || 'stable';
  const eGFRChange = toNumber(patient.latest_observations?.eGFR_change);
  const uACR = toNumber(patient.latest_observations?.uACR);
  const proteinuriaCategory = patient.latest_observations?.proteinuria_category;
  const systolicBP = toNumber(patient.latest_observations?.blood_pressure?.systolic);
  const diastolicBP = toNumber(patient.latest_observations?.blood_pressure?.diastolic);
  const hba1c = toNumber(patient.latest_observations?.HbA1c);
  const hemoglobin = toNumber(patient.latest_observations?.hemoglobin);
  const potassium = toNumber(patient.latest_observations?.potassium);
  const phosphorus = toNumber(patient.latest_observations?.phosphorus);
  const bmi = toNumber(patient.latest_observations?.BMI);

  // Get CKD stage as number
  const ckdStageStr = patient.ckd_stage || '1';
  const ckdStage = parseInt(ckdStageStr.replace('a', '').replace('b', ''), 10);

  // Build comorbidities list
  const comorbidities: string[] = [];
  if (patient.has_diabetes) comorbidities.push('Diabetes');
  if (patient.has_hypertension) comorbidities.push('Hypertension');
  if (patient.cvd_history) comorbidities.push('CVD');

  // =================================================================
  // CRITICAL ALERTS (10 points each)
  // =================================================================

  // 1. Rapid eGFR Decline (>10% decline)
  if (eGFRTrend === 'down' && eGFRChange <= -10) {
    alerts.push({
      severity: 'CRITICAL',
      code: 'RAPID_DECLINE',
      message: `Rapid eGFR decline (${eGFRChange.toFixed(1)}%)`,
      action: 'Urgent nephrology referral, investigate reversible causes (AKI, medications, obstruction)'
    });
    severity_score += 10;
  }

  // 2. Severe CKD Without Specialist (Stage 4-5)
  if (ckdStage >= 4 && !patient.nephrologist_referral) {
    alerts.push({
      severity: 'CRITICAL',
      code: 'NO_SPECIALIST',
      message: `Stage ${ckdStage} CKD without nephrologist`,
      action: 'IMMEDIATE nephrology referral - dialysis planning may be needed'
    });
    severity_score += 10;
  }

  // 3. Dangerous Hyperkalemia (K+ >6.0)
  if (potassium > 6.0) {
    alerts.push({
      severity: 'CRITICAL',
      code: 'HYPERKALEMIA',
      message: `Severe hyperkalemia (K+ ${potassium.toFixed(1)} mEq/L)`,
      action: 'IMMEDIATE evaluation - cardiac monitoring, stop K+-sparing agents, consider dialysis'
    });
    severity_score += 10;
  }

  // 4. Severe Anemia (Hb <9.0 in Stage 3+)
  if (hemoglobin < 9.0 && ckdStage >= 3) {
    alerts.push({
      severity: 'CRITICAL',
      code: 'SEVERE_ANEMIA',
      message: `Severe anemia (Hb ${hemoglobin.toFixed(1)} g/dL)`,
      action: 'Urgent investigation: iron studies, B12/folate, GI evaluation; consider ESA therapy'
    });
    severity_score += 10;
  }

  // 5. Nephrotic-Range Proteinuria with Decline
  if (uACR > 300 && eGFRTrend === 'down') {
    alerts.push({
      severity: 'CRITICAL',
      code: 'NEPHROTIC_DECLINE',
      message: `Nephrotic-range proteinuria (uACR ${uACR.toFixed(0)} mg/g) with declining eGFR`,
      action: 'Urgent nephrology referral - consider kidney biopsy, exclude glomerulonephritis'
    });
    severity_score += 10;
  }

  // =================================================================
  // HIGH PRIORITY ALERTS (5 points each)
  // =================================================================

  // 6. Heavy Proteinuria (A3 category)
  if (proteinuriaCategory === 'A3' && uACR <= 300) {
    alerts.push({
      severity: 'HIGH',
      code: 'HEAVY_PROTEINURIA',
      message: `Heavy proteinuria (A3, uACR ${uACR.toFixed(0)} mg/g)`,
      action: 'Optimize RAS inhibition (ACE-I/ARB), add SGLT2i if diabetic'
    });
    severity_score += 5;
  }

  // 7. Uncontrolled Hypertension in Stage 3+
  if ((systolicBP >= 140 || diastolicBP >= 90) && ckdStage >= 3) {
    alerts.push({
      severity: 'HIGH',
      code: 'UNCONTROLLED_HTN',
      message: `Uncontrolled hypertension (${systolicBP.toFixed(0)}/${diastolicBP.toFixed(0)} mmHg)`,
      action: 'Intensify antihypertensive therapy - target <130/80 in CKD with proteinuria'
    });
    severity_score += 5;
  }

  // 8. Uncontrolled Diabetes (HbA1c >7.5%)
  if (hba1c > 7.5 && patient.has_diabetes) {
    alerts.push({
      severity: 'HIGH',
      code: 'UNCONTROLLED_DM',
      message: `Uncontrolled diabetes (HbA1c ${hba1c.toFixed(1)}%)`,
      action: 'Optimize glycemic control - target HbA1c <7%, strongly consider SGLT2i'
    });
    severity_score += 5;
  }

  // 9. Hyperphosphatemia in Stage 4+
  if (phosphorus > 4.5 && ckdStage >= 4) {
    alerts.push({
      severity: 'HIGH',
      code: 'HYPERPHOSPHATEMIA',
      message: `Elevated phosphorus (${phosphorus.toFixed(1)} mg/dL)`,
      action: 'Dietary counseling (limit high-phosphate foods), initiate phosphate binders'
    });
    severity_score += 5;
  }

  // 10. Nephrotoxic Medications with Decline
  if (patient.nephrotoxic_meds && eGFRTrend === 'down') {
    alerts.push({
      severity: 'HIGH',
      code: 'NEPHROTOXIC_MEDS',
      message: 'Nephrotoxic medications with declining kidney function',
      action: 'URGENT medication review - discontinue/substitute NSAIDs, aminoglycosides, etc.'
    });
    severity_score += 5;
  }

  // 11. Moderate Anemia (9-11 g/dL in Stage 3+)
  if (hemoglobin >= 9.0 && hemoglobin < 11.0 && ckdStage >= 3) {
    alerts.push({
      severity: 'HIGH',
      code: 'MODERATE_ANEMIA',
      message: `Moderate anemia (Hb ${hemoglobin.toFixed(1)} g/dL)`,
      action: 'Iron studies, address iron deficiency, monitor for progression'
    });
    severity_score += 5;
  }

  // 12. Moderate Hyperkalemia (5.5-6.0)
  if (potassium > 5.5 && potassium <= 6.0) {
    alerts.push({
      severity: 'HIGH',
      code: 'MODERATE_HYPERKALEMIA',
      message: `Moderate hyperkalemia (K+ ${potassium.toFixed(1)} mEq/L)`,
      action: 'Dietary counseling, review medications, consider K+ binder if persistent'
    });
    severity_score += 5;
  }

  // =================================================================
  // MODERATE ALERTS (2 points each)
  // =================================================================

  // 13. Missing RAS Inhibitor (proteinuria without ACE-I/ARB)
  if (ckdStage >= 2 && uACR > 30 && !patient.on_ras_inhibitor) {
    alerts.push({
      severity: 'MODERATE',
      code: 'NO_RAS_INHIBITOR',
      message: 'Proteinuria without RAS inhibitor therapy',
      action: 'Initiate ACE inhibitor or ARB (first-line for proteinuric CKD)'
    });
    severity_score += 2;
  }

  // 14. Missing SGLT2i in Diabetic CKD
  if (patient.has_diabetes && ckdStage >= 2 && !patient.on_sglt2i && eGFR >= 20) {
    alerts.push({
      severity: 'MODERATE',
      code: 'NO_SGLT2I',
      message: 'Diabetic CKD without SGLT2 inhibitor',
      action: 'Consider SGLT2i (empagliflozin/dapagliflozin) - proven renoprotection'
    });
    severity_score += 2;
  }

  // 15. Obesity (BMI ≥30)
  if (bmi >= 30 && ckdStage >= 2) {
    alerts.push({
      severity: 'MODERATE',
      code: 'OBESITY',
      message: `Obesity (BMI ${bmi.toFixed(1)} kg/m²)`,
      action: 'Weight management program - target 5-10% weight loss, dietary counseling'
    });
    severity_score += 2;
  }

  // 16. Active Smoking
  if (patient.smoking_status === 'Current' && ckdStage >= 2) {
    alerts.push({
      severity: 'MODERATE',
      code: 'ACTIVE_SMOKING',
      message: 'Active smoker - accelerates CKD progression',
      action: 'Smoking cessation counseling, pharmacotherapy (varenicline, bupropion)'
    });
    severity_score += 2;
  }

  // 17. Stage 3+ with declining function
  if (ckdStage >= 3 && eGFRTrend === 'down' && eGFRChange < -5 && eGFRChange > -10) {
    alerts.push({
      severity: 'MODERATE',
      code: 'PROGRESSIVE_CKD',
      message: `Progressive CKD (Stage ${ckdStage}, eGFR declining ${eGFRChange.toFixed(1)}%)`,
      action: 'Review medications, optimize BP/DM control, ensure nephrology follow-up'
    });
    severity_score += 2;
  }

  // Determine priority level
  let priority: MonitoringPriority;
  if (severity_score >= 20) {
    priority = 'CRITICAL';
  } else if (severity_score >= 10) {
    priority = 'HIGH';
  } else if (severity_score >= 5) {
    priority = 'MODERATE';
  } else {
    priority = 'LOW';
  }

  return {
    patient_id: patient.id,
    name: patient.full_name,
    mrn: patient.medical_record_number,
    age: patient.age,
    gender: patient.gender,
    stage: ckdStage,
    egfr: eGFR,
    egfr_trend: eGFRTrend,
    egfr_change: eGFRChange,
    comorbidities,
    alerts,
    alert_count: alerts.length,
    severity_score,
    priority,
    requires_monitoring: alerts.length > 0
  };
}

/**
 * Scan entire patient database and identify high-risk patients
 */
export async function scanPatientDatabase(): Promise<ScanResults> {
  // Get all patients
  const patients = await getPatientList();

  // Assess each patient
  const assessments = patients.map(patient => assessPatientRisk(patient));

  // Filter for high-risk patients only
  const highRiskPatients = assessments.filter(a => a.requires_monitoring);

  // Sort by severity score (highest first)
  highRiskPatients.sort((a, b) => b.severity_score - a.severity_score);

  // Calculate statistics
  const priorityDistribution = {
    CRITICAL: highRiskPatients.filter(p => p.priority === 'CRITICAL').length,
    HIGH: highRiskPatients.filter(p => p.priority === 'HIGH').length,
    MODERATE: highRiskPatients.filter(p => p.priority === 'MODERATE').length
  };

  // Calculate alert frequency
  const alertFrequency: Record<string, number> = {};
  for (const patient of highRiskPatients) {
    for (const alert of patient.alerts) {
      alertFrequency[alert.code] = (alertFrequency[alert.code] || 0) + 1;
    }
  }

  // Sort alert frequency by count (descending)
  const sortedAlertFrequency: Record<string, number> = {};
  Object.entries(alertFrequency)
    .sort(([, a], [, b]) => b - a)
    .forEach(([code, count]) => {
      sortedAlertFrequency[code] = count;
    });

  return {
    scan_date: new Date().toISOString(),
    total_patients_scanned: patients.length,
    high_risk_patients: highRiskPatients.length,
    high_risk_percentage: parseFloat(((highRiskPatients.length / patients.length) * 100).toFixed(1)),
    priority_distribution: priorityDistribution,
    alert_frequency: sortedAlertFrequency,
    patients: highRiskPatients
  };
}

/**
 * Get high-risk patients filtered by priority
 */
export async function getHighRiskPatientsByPriority(
  priority: MonitoringPriority
): Promise<HighRiskPatientAssessment[]> {
  const results = await scanPatientDatabase();
  return results.patients.filter(p => p.priority === priority);
}

/**
 * Get critical priority patients (immediate action required)
 */
export async function getCriticalPatients(): Promise<HighRiskPatientAssessment[]> {
  return getHighRiskPatientsByPriority('CRITICAL');
}
